module {
  // Keep this library textual source as the authority; LLVM bytecode is
  // version-sensitive and must be regenerated by the current mlir-opt.
  func.func private @_avelang_amdgpu_llvm_amdgcn_perm(%arg0: i32, %arg1: i32, %arg2: i32) -> i32 attributes {func.inline = "always"} {
    %0 = llvm.call_intrinsic "llvm.amdgcn.perm"(%arg0, %arg1, %arg2) : (i32, i32, i32) -> i32
    return %0 : i32
  }

  func.func private @_avelang_amdgpu_llvm_amdgcn_rcp_f32(%arg0: f32) -> f32 attributes {func.inline = "always"} {
    %0 = llvm.call_intrinsic "llvm.amdgcn.rcp.f32"(%arg0) : (f32) -> f32
    return %0 : f32
  }

  func.func private @_avelang_amdgpu_llvm_amdgcn_s_waitcnt(%arg0: i32) attributes {func.inline = "always"} {
    llvm.call_intrinsic "llvm.amdgcn.s.waitcnt"(%arg0) : (i32) -> ()
    return
  }

  func.func private @_avelang_amdgpu_rocdl_mfma_f32_16x16x16_f16(%arg0: vector<2xi32>, %arg1: vector<2xi32>, %arg2: vector<4xf32>) -> vector<4xf32> attributes {func.inline = "always"} {
    %c0_i32 = arith.constant 0 : i32
    %a_f16 = vector.bitcast %arg0 : vector<2xi32> to vector<4xf16>
    %b_f16 = vector.bitcast %arg1 : vector<2xi32> to vector<4xf16>
    %3 = rocdl.mfma.f32.16x16x16f16 %a_f16, %b_f16, %arg2, %c0_i32, %c0_i32, %c0_i32 : (vector<4xf16>, vector<4xf16>, vector<4xf32>, i32, i32, i32) -> vector<4xf32>
    return %3 : vector<4xf32>
  }

  func.func private @_avelang_amdgpu_rocdl_mfma_f32_16x16x16bf16_1k(%arg0: vector<2xi32>, %arg1: vector<2xi32>, %arg2: vector<4xf32>) -> vector<4xf32> attributes {func.inline = "always"} {
    %c0_i32 = arith.constant 0 : i32
    %a_i16 = vector.bitcast %arg0 : vector<2xi32> to vector<4xi16>
    %b_i16 = vector.bitcast %arg1 : vector<2xi32> to vector<4xi16>
    %3 = rocdl.mfma.f32.16x16x16bf16.1k %a_i16, %b_i16, %arg2, %c0_i32, %c0_i32, %c0_i32 : (vector<4xi16>, vector<4xi16>, vector<4xf32>, i32, i32, i32) -> vector<4xf32>
    return %3 : vector<4xf32>
  }

  func.func private @_avelang_amdgpu_rocdl_mfma_f32_32x32x8bf16_1k(%arg0: vector<2xi32>, %arg1: vector<2xi32>, %arg2: vector<16xf32>) -> vector<16xf32> attributes {func.inline = "always"} {
    %c0_i32 = arith.constant 0 : i32
    %a_i16 = vector.bitcast %arg0 : vector<2xi32> to vector<4xi16>
    %b_i16 = vector.bitcast %arg1 : vector<2xi32> to vector<4xi16>
    %3 = rocdl.mfma.f32.32x32x8bf16.1k %a_i16, %b_i16, %arg2, %c0_i32, %c0_i32, %c0_i32 : (vector<4xi16>, vector<4xi16>, vector<16xf32>, i32, i32, i32) -> vector<16xf32>
    return %3 : vector<16xf32>
  }

  func.func private @_avelang_amdgpu_rocdl_mfma_f32_16x16x32_fp8_fp8(%arg0: vector<2xi32>, %arg1: vector<2xi32>, %arg2: vector<4xf32>) -> vector<4xf32> attributes {func.inline = "always"} {
    %c0_i32 = arith.constant 0 : i32
    %a_v1 = vector.bitcast %arg0 : vector<2xi32> to vector<1xi64>
    %b_v1 = vector.bitcast %arg1 : vector<2xi32> to vector<1xi64>
    %a_i64 = vector.extract %a_v1[0] : i64 from vector<1xi64>
    %b_i64 = vector.extract %b_v1[0] : i64 from vector<1xi64>
    %3 = rocdl.mfma.f32.16x16x32.fp8.fp8 %a_i64, %b_i64, %arg2, %c0_i32, %c0_i32, %c0_i32 : (i64, i64, vector<4xf32>, i32, i32, i32) -> vector<4xf32>
    return %3 : vector<4xf32>
  }

}
